fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

default:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

admin:
    path:      /admin
    defaults:  { _controller: AppBundle:Admin:main }

admin_upload:
    path:      /admin/upload
    defaults:  { _controller: AppBundle:Admin:upload }

admin_tag:
    path:      /admin/tag
    defaults:  { _controller: AppBundle:Admin:tag }

admin_doc:
    path:      /admin/doc
    defaults:  { _controller: AppBundle:Admin:doc }

admin_train:
    path:      /admin/train
    defaults:  { _controller: AppBundle:Admin:train }

admin_dashboard:
    path:      /admin/dashboard
    defaults:  { _controller: AppBundle:Admin:dashboard }

admin_setting:
    path:      /admin/setting
    defaults:  { _controller: AppBundle:Admin:setting }

admin_file:
    path:      /admin/file/{fileId}
    defaults:  { _controller: AppBundle:Admin:file }

admin_query:
    path:      /admin/query
    defaults:  { _controller: AppBundle:Admin:query }    

service_upload_files:
    path:      /service/upload_files
    defaults:  { _controller: AppBundle:Service:uploadFile }

service_upload_crawl:
    path:      /service/upload_crawl
    defaults:  { _controller: AppBundle:Service:uploadCrawl }
    methods:  [POST]

service_untagged:
    path:      /service/untagged
    defaults:  { _controller: AppBundle:Service:untagged }

service_untagged_file:
    path:      /service/untagged_file/{fileId}
    defaults:  { _controller: AppBundle:Service:untaggedFile }

service_untagged_file_update:
    path:      /service/untagged_file/{fileId}/{paragraphId}
    defaults:  { _controller: AppBundle:Service:untaggedParagraphUpdate }
    methods:  [POST]

service_tag_structure:
    path:      /service/tag_structure
    defaults:  { _controller: AppBundle:Service:tagStructure }
    methods:  [GET, HEAD]

service_tag_structure_update:
    path:      /service/tag_structure
    defaults:  { _controller: AppBundle:Service:updateTagStructure }  
    methods:  [POST]